package com.tasks.usertrack.db.models;

import java.math.BigDecimal;
import java.util.Date;

public class Track {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column track.lat
     *
     * @mbg.generated Sat Mar 14 16:42:53 OMST 2020
     */
    private BigDecimal lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column track.lng
     *
     * @mbg.generated Sat Mar 14 16:42:53 OMST 2020
     */
    private BigDecimal lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column track.created_at
     *
     * @mbg.generated Sat Mar 14 16:42:53 OMST 2020
     */
    private Date created_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column track.user_id
     *
     * @mbg.generated Sat Mar 14 16:42:53 OMST 2020
     */
    private Integer user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column track.lat
     *
     * @return the value of track.lat
     *
     * @mbg.generated Sat Mar 14 16:42:53 OMST 2020
     */
    public BigDecimal getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column track.lat
     *
     * @param lat the value for track.lat
     *
     * @mbg.generated Sat Mar 14 16:42:53 OMST 2020
     */
    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column track.lng
     *
     * @return the value of track.lng
     *
     * @mbg.generated Sat Mar 14 16:42:53 OMST 2020
     */
    public BigDecimal getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column track.lng
     *
     * @param lng the value for track.lng
     *
     * @mbg.generated Sat Mar 14 16:42:53 OMST 2020
     */
    public void setLng(BigDecimal lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column track.created_at
     *
     * @return the value of track.created_at
     *
     * @mbg.generated Sat Mar 14 16:42:53 OMST 2020
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column track.created_at
     *
     * @param created_at the value for track.created_at
     *
     * @mbg.generated Sat Mar 14 16:42:53 OMST 2020
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column track.user_id
     *
     * @return the value of track.user_id
     *
     * @mbg.generated Sat Mar 14 16:42:53 OMST 2020
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column track.user_id
     *
     * @param user_id the value for track.user_id
     *
     * @mbg.generated Sat Mar 14 16:42:53 OMST 2020
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}